---
- name: Check if clewarecontrol is already installed.
  stat:
    path: /bin/clewarecontrol
  register: _clewarecontrol_stat_result

- name: Install clewarecontrol.
  block:
    - name: Clone clewarecontrol repo.
      git:
        repo: "https://github.com/flok99/clewarecontrol.git"
        dest: "{{ jxfd_clewarecontrol_basedir }}"
        version: "{{ jxfd_clewarecontrol_version }}"

    - name: Compile clewarecontrol
      shell: make install
      args:
        chdir: "{{ jxfd_clewarecontrol_basedir }}"
      tags:
        - skip_ansible_lint

  when: not _clewarecontrol_stat_result.stat.exists

- name: Grant access to usb.
  blockinfile:
    path: /etc/udev/rules.d/10-local.rules
    marker: "# {mark} ANSIBLE MANAGED BLOCK - jxfd"
    block: |
      ATTRS{idVendor}=="0d50", MODE="0660", GROUP="{{ jxfd_group }}"
    create: yes
  notify:
    - udevadm reload-rules
    - restart jxfd
