- name: Install OS packages.
  package:
    name: "{{ jefd_os_packages }}"
  tags:
    - packages
    - apt
    - install

- name: Install pip packages.
  pip:
    name: "{{ jefd_pip_packages }}"
  tags:
    - packages
    - pip
    - install

- name: Create  group.
  group:
    name: "{{ jefd_group }}"
  tags:
    - user
    - install

- name: Create user.
  user:
    name: "{{ jefd_owner }}"
    group: "{{ jefd_group }}"
  tags:
    - user
    - install

- include_tasks: clewarecontrol.yaml
  tags:
    - install

- name: Create directory.
  file:
    path: "{{ jefd_basedir }}"
    owner: "{{ jefd_owner }}"
    group: "{{ jefd_group }}"
    state: directory
  tags:
    - install

- name: Change ownership on www dir
  file:
    path: "{{ jenkins_feedback_device_docroot }}"
    owner: "{{ jefd_owner }}"
    group: "{{ jefd_group }}"
    state: directory
    recurse: yes
  tags:
    - install

- name: Deploy client script.
  copy:
    src: client.py
    dest: "{{ jefd_script }}"
    owner: "{{ jefd_owner }}"
    group: "{{ jefd_group }}"
  tags:
    - config
  notify:
    - restart jefd

- name: Deploy additional files.
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest | default(jefd_basedir) }}"
    owner: "{{ jefd_owner }}"
    group: "{{ jefd_group }}"
  with_items:
    - src: index.html.j2
  tags:
    - files
  notify:
    - restart jefd

- name: Deploy config.
  template:
    src: templates/opt/jefd/config.yml.j2
    dest: "{{ jefd_config }}"
    owner: "{{ jefd_owner }}"
    group: "{{ jefd_group }}"
  tags:
    - config
  notify:
    - restart jefd

- name: Deploy systemd service file.
  template:
    src: templates/etc/systemd/system/jefd.service.j2
    dest: /etc/systemd/system/jefd.service
  register: _service_result
  tags:
    - config
  notify:
    - restart jefd

- name: Enable and start service.
  systemd:
    name: jefd
    enabled: yes
    state: started
    daemon_reload: "{{ _service_result.changed }}"
  tags:
    - config