---
- name: Install OS packages.
  package:
    name: "{{ jxfd_os_packages }}"
  tags:
    - packages
    - apt
    - install

- name: Install pip packages.
  pip:
    name: "{{ jxfd_pip_packages }}"
  tags:
    - packages
    - pip
    - install

- name: Create group.
  group:
    name: "{{ jxfd_group }}"
  tags:
    - user
    - install

- name: Create user.
  user:
    name: "{{ jxfd_owner }}"
    group: "{{ jxfd_group }}"
  tags:
    - user
    - install

- include_tasks: clewarecontrol.yaml
  tags:
    - install

- name: Create directory.
  file:
    path: "{{ jxfd_basedir }}"
    owner: "{{ jxfd_owner }}"
    group: "{{ jxfd_group }}"
    state: directory
    mode: "0755"
  tags:
    - install

- name: Change ownership on www dir
  file:
    path: "{{ jenkins_feedback_device_docroot }}"
    owner: "{{ jxfd_owner }}"
    group: "{{ jxfd_group }}"
    state: directory
    mode: "0755"
    recurse: yes
  tags:
    - install

- name: Deploy client script.
  copy:
    src: client.py
    dest: "{{ jxfd_script }}"
    owner: "{{ jxfd_owner }}"
    group: "{{ jxfd_group }}"
    mode: "0644"
  tags:
    - client
  notify:
    - restart jxfd

- name: Deploy html resources.
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest | default(jxfd_basedir) }}"
    owner: "{{ jxfd_owner }}"
    group: "{{ jxfd_group }}"
    mode: "0644"
  with_items:
    - src: html/
      dest: /var/www/html/
  tags:
    - files
    - resources
  notify:
    - restart jxfd

- name: Deploy additional files.
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest | default(jxfd_basedir) }}"
    owner: "{{ jxfd_owner }}"
    group: "{{ jxfd_group }}"
    mode: "0644"
  with_items:
    - src: index.html.j2
  tags:
    - files
    - template
  notify:
    - restart jxfd

- name: Deploy config.
  template:
    src: templates/opt/jxfd/config.yml.j2
    dest: "{{ jxfd_config }}"
    owner: "{{ jxfd_owner }}"
    group: "{{ jxfd_group }}"
    mode: "0644"
  tags:
    - config
  notify:
    - restart jxfd

- name: Deploy systemd service file.
  template:
    src: templates/etc/systemd/system/jxfd.service.j2
    dest: /etc/systemd/system/jxfd.service
    mode: "0644"
  register: _service_result
  tags:
    - service
  notify:
    - restart jxfd

- name: Enable and start service.
  systemd:
    name: jxfd
    enabled: yes
    state: started
    daemon_reload: "{{ _service_result.changed }}"
  tags:
    - config
